---
- hosts: bxine
  remote_user: '{{ user_1_name }}' #root
  become: true
  vars:
    server_ip: "{{ bxine_ip }}"
  vars_files:
    - './secrets/users_secrets.yml'

  roles:
    - { role: base_packages, tags: base }
    - { role: create_users, users: "{{ server_users }}" }
    - { role: development_user, users: "{{ server_users }}" }
    - { role: nginx, tags: nginx, mina_deploy: true }
