---
- name: Add key for apt
  apt_key:
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
    keyserver: pgp.mit.edu
    state: present

- name: Add Dropbox repository
  apt_repository:
    repo: deb http://linux.dropbox.com/ubuntu xenial main
    state: present

- name: Install Dropbox
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: present
  with_items:
    - dropbox
    - python-gpgme

# Does not work
#- name: start dropbox daemon
#  shell: dropbox start -i
# TODO Manually:
# ~/.dropbox-dist/dropboxd
# validate online
# dropbox exclude item item

- name: Exlude some folder
  shell: dropbox exclude anti-ennui discovery ebooks-old ensiie epresse filter_img logs

- name: Dropbox auto-start
  shell: dropbox autostart y
